import{a as L,S as b,i as n}from"./assets/vendor-Dpd1z_xS.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();async function f(r,s){return await L.get("https://pixabay.com/api//?image_type=photo&orientation=horizontal&safesearch=true&key=47395064-b7fd47e3542f1aea6492dfd3a",{params:{q:r,page:s,per_page:15}})}function h(r){return r.map(({webformatURL:s,largeImageURL:i,tags:a,likes:e,views:t,comments:l,downloads:y})=>`<li class="list-item" >
    <a href="${i}" alt="${a}" title=""/>
    <img src="${s}" alt="${a}" class="img-item">
    <div class="list-container">
    <p class="item"><span class="item-text">Likes</span> <span>${e}</span></p>
    <p class="item"><span class="item-text">Views</span> <span>${t}</span></p>
    <p class="item"><span class="item-text">Comments</span> <span>${l}</span></p>
    <p class="item"><span class="item-text">Downloads</span> <span>${y}</span></p>
    </div></a>
  </li>`).join("")}const g=new b(".list-js a",{captionsData:"alt",captionDelay:250,captionClass:"imageTitle"}),w=document.querySelector(".form-js"),p=document.querySelector(".list-js"),m=document.querySelector(".loader"),o=document.querySelector(".js-load-btn");w.addEventListener("submit",P);o.addEventListener("click",S);let c=1,u=1,d="";function P(r){r.preventDefault();const{picture:s}=r.target.elements;if(d=s.value.trim(),p.innerHTML="",!d){n.show({title:"Error",message:"Please add request!",position:"center"});return}c=1,m.classList.remove("hidden"),o.classList.replace("more-btn","hidden"),f(d,c).then(({data:{hits:i,totalHits:a}})=>{if(u=Math.ceil(a/15),!i.length){n.show({title:"No Results",message:"Please enter a valid search query!",position:"center"});return}p.innerHTML=h(i),g.refresh(),u===1?(n.show({title:"End of Results",message:"No more images found for your query.",position:"center"}),o.classList.replace("more-btn","hidden")):o.classList.replace("hidden","more-btn")}).catch(i=>{n.show({title:"Error",message:`Something went wrong: ${i.message}. Please try again later.`,position:"center"})}).finally(()=>{s.value="",m.classList.add("hidden")})}async function S(){c+=1,o.disabled=!0,m.classList.remove("hidden");try{const{data:{hits:r,totalHits:s}}=await f(d,c);p.insertAdjacentHTML("beforeend",h(r)),g.refresh(),(c>=u||!s)&&(o.classList.replace("more-btn","hidden"),n.show({title:"End of results",message:"Sorry, there are no more images matching your request.",position:"center"}));const a=document.querySelector(".list-item").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2.5,behavior:"smooth"})}catch(r){n.show({title:"Error",message:`Something went wrong: ${r.message}. Please try again later.`,position:"center"})}finally{m.classList.add("hidden"),o.disabled=!1}}
//# sourceMappingURL=index.js.map
