import{a as y,S as L,i as c}from"./assets/vendor-Dpd1z_xS.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&t(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function t(e){if(e.ep)return;e.ep=!0;const i=n(e);fetch(e.href,i)}})();async function u(s,a){return await y.get(`https://pixabay.com/api//?q=${s}&image_type=photo&orientation=horizontal&safesearch=true&key=47395064-b7fd47e3542f1aea6492dfd3a`,{params:{page:a,per_page:15}})}function f(s){return s.map(({webformatURL:a,largeImageURL:n,tags:t,likes:e,views:i,comments:l,downloads:h})=>`<li class="list-item" >
    <a href="${n}" alt="${t}" title=""/>
    <img src="${a}" alt="${t}" class="img-item">
    <div class="list-container">
    <p class="item"><span class="item-text">Likes</span> <span>${e}</span></p>
    <p class="item"><span class="item-text">Views</span> <span>${i}</span></p>
    <p class="item"><span class="item-text">Comments</span> <span>${l}</span></p>
    <p class="item"><span class="item-text">Downloads</span> <span>${h}</span></p>
    </div></a>
  </li>`).join("")}const g=new L(".list-js a",{captionsData:"alt",captionDelay:250,captionClass:"imageTitle"}),b=document.querySelector(".form-js"),d=document.querySelector(".list-js"),p=document.querySelector(".loader"),r=document.querySelector(".js-load-btn");b.addEventListener("submit",w);r.addEventListener("click",P);let o=1,m=1;function w(s){s.preventDefault();const{picture:a}=s.target.elements,n=a.value.trim();if(d.innerHTML="",!n||n===" "){c.show({title:"Error",message:"Please add request!",position:"center"}),d.innerHTML="";return}o=1,p.classList.remove("hidden"),r.classList.replace("more-btn","hidden"),u(n,o).then(({data:{hits:t,totalHits:e}})=>{m=Math.ceil(e/t.length),console.log(o),t.length?(d.innerHTML=f(t),g.refresh(),o>=m&&r.classList.replace("more-btn","hidden"),r.classList.replace("hidden","more-btn")):c.show({title:"No Results",message:"Please enter a valid search query!",position:"center"})}).catch(t=>{console.log(t.message),c.show({title:"Error",message:`Something went wrong: ${t.message}. Please try again later.`,position:"center"})}).finally(()=>{a.value="",p.classList.add("hidden")})}async function P(){o+=1,r.disabled=!0;try{const{data:{hits:s,totalHits:a}}=await u(o);d.insertAdjacentHTML("beforeend",f(s)),m=Math.ceil(a/s.length),(o>=m||!a)&&(r.classList.replace("more-btn","hidden"),c.show({title:"End of results",message:"Sorry, there are no more images matching your request.",position:"center"}));const t=document.querySelector(".list-item").getBoundingClientRect().height;window.scrollBy({left:0,top:t*2.5,behavior:"smooth"}),g.refresh()}catch(s){console.log(s.message),c.show({title:"Error",message:`Something went wrong: ${s.message}. Please try again later.`,position:"center"})}finally{r.disabled=!1}}
//# sourceMappingURL=index.js.map
